// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	orders "laundro-api-ca/business/orders"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: userId, orderData
func (_m *Service) Create(userId uint, orderData *orders.Domain) (orders.Domain, error) {
	ret := _m.Called(userId, orderData)

	var r0 orders.Domain
	if rf, ok := ret.Get(0).(func(uint, *orders.Domain) orders.Domain); ok {
		r0 = rf(userId, orderData)
	} else {
		r0 = ret.Get(0).(orders.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *orders.Domain) error); ok {
		r1 = rf(userId, orderData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: userId
func (_m *Service) GetByUserID(userId uint) ([]orders.Domain, error) {
	ret := _m.Called(userId)

	var r0 []orders.Domain
	if rf, ok := ret.Get(0).(func(uint) []orders.Domain); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orders.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
