// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	addresses "laundro-api-ca/business/addresses"
	laundromats "laundro-api-ca/business/laundromats"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id uint) (string, error) {
	ret := _m.Called(id)

	var r0 string
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *Service) GetByID(id uint) (laundromats.Domain, error) {
	ret := _m.Called(id)

	var r0 laundromats.Domain
	if rf, ok := ret.Get(0).(func(uint) laundromats.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(laundromats.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIP provides a mock function with given fields: ip
func (_m *Service) GetByIP(ip string) ([]laundromats.Domain, error) {
	ret := _m.Called(ip)

	var r0 []laundromats.Domain
	if rf, ok := ret.Get(0).(func(string) []laundromats.Domain); ok {
		r0 = rf(ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]laundromats.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: name
func (_m *Service) GetByName(name string) ([]laundromats.Domain, error) {
	ret := _m.Called(name)

	var r0 []laundromats.Domain
	if rf, ok := ret.Get(0).(func(string) []laundromats.Domain); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]laundromats.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: userID, laundroData, addressData
func (_m *Service) Insert(userID uint, laundroData *laundromats.Domain, addressData *addresses.Domain) (laundromats.Domain, error) {
	ret := _m.Called(userID, laundroData, addressData)

	var r0 laundromats.Domain
	if rf, ok := ret.Get(0).(func(uint, *laundromats.Domain, *addresses.Domain) laundromats.Domain); ok {
		r0 = rf(userID, laundroData, addressData)
	} else {
		r0 = ret.Get(0).(laundromats.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *laundromats.Domain, *addresses.Domain) error); ok {
		r1 = rf(userID, laundroData, addressData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, laundroData, addressData
func (_m *Service) Update(id uint, laundroData *laundromats.Domain, addressData *addresses.Domain) (laundromats.Domain, error) {
	ret := _m.Called(id, laundroData, addressData)

	var r0 laundromats.Domain
	if rf, ok := ret.Get(0).(func(uint, *laundromats.Domain, *addresses.Domain) laundromats.Domain); ok {
		r0 = rf(id, laundroData, addressData)
	} else {
		r0 = ret.Get(0).(laundromats.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *laundromats.Domain, *addresses.Domain) error); ok {
		r1 = rf(id, laundroData, addressData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
