name: AWS EC2 CI/ID

on:
  push:
    branches:
      - "ci/cd"
  pull_request:
    branches:
      - "ci/cd"

jobs:
  unit-test:
    name: "unit testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: running unit testing
        run: go test ./... -cover

  build-push-docker:
    name: Build docker image then push to docker hub
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: docker build -t mugeki/laundro-api:1.0.0 .
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to docker hub
        run: docker push mugeki/laundro-api:1.0.0

  deployment-ec2-aws:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - name: Connect to EC2 and run docker
        uses: appleboy/ssh-action@master
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          PORT: ${{ secrets.PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRED: ${{ secrets.JWT_EXPIRED }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: PORT,DB_USER,DB_PASSWORD,DB_HOST,DB_PORT,DB_NAME,JWT_EXPIRED,JWT_SECRET
          script: |
            docker rm -vf $(docker ps -a -q) && \
            docker pull mugeki/laundro-api:1.0.0 && \
            docker run -d -p 8000:8000 --name laundro-api \
            -e PORT=$PORT \
            -e DB_HOST=$HOST \
            -e DB_PORT=$DB_PORT \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_NAME=$DB_NAME \
            -e JWT_SECRET=$JWT_SECRET \
            -e JWT_EXPIRED=$JWT_EXPIRED \
            mugeki/laundro-api:1.0.0
